name: Purge-Database

on:
  workflow_dispatch:

  schedule:
    - cron: "44 2 */30 * *"

jobs:
  Purge:
    name: Purge Database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel
      - name: Cache pipenv
        uses: actions/cache@v2
        id: cache-pipenv
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: ${{ runner.os }}-pipenv-
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv install
      - name: Purge
        env:
          DATABASE: ${{ secrets.DATABASE }}
          EXPIRE_TIME: ${{ secrets.EXPIRE_TIME }}
        run: pipenv run python ./clean.py || echo 'Check your configuration.'
